# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='eventhandling.proto',
  package='eventstreaming',
  serialized_pb='\n\x13\x65venthandling.proto\x12\x0e\x65ventstreaming\"\xb7\x01\n\x0c\x45ventRequest\x12;\n\x04type\x18\x01 \x02(\x0e\x32-.eventstreaming.EventRequest.EventRequestType\x12<\n\x0b\x65vent_range\x18\x02 \x01(\x0b\x32\'.eventstreaming.EventStreamRangeRequest\",\n\x10\x45ventRequestType\x12\x18\n\x14RANGE_STREAM_REQUEST\x10\x02\"2\n\x17\x45ventStreamRangeRequest\x12\x0b\n\x03\x66ro\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\"-\n\x0bStoredEvent\x12\x0f\n\x07\x65ventid\x18\x01 \x02(\t\x12\r\n\x05\x65vent\x18\x02 \x02(\x0c')



_EVENTREQUEST_EVENTREQUESTTYPE = descriptor.EnumDescriptor(
  name='EventRequestType',
  full_name='eventstreaming.EventRequest.EventRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RANGE_STREAM_REQUEST', index=0, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=223,
)


_EVENTREQUEST = descriptor.Descriptor(
  name='EventRequest',
  full_name='eventstreaming.EventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='eventstreaming.EventRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_range', full_name='eventstreaming.EventRequest.event_range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTREQUEST_EVENTREQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=223,
)


_EVENTSTREAMRANGEREQUEST = descriptor.Descriptor(
  name='EventStreamRangeRequest',
  full_name='eventstreaming.EventStreamRangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fro', full_name='eventstreaming.EventStreamRangeRequest.fro', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to', full_name='eventstreaming.EventStreamRangeRequest.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=275,
)


_STOREDEVENT = descriptor.Descriptor(
  name='StoredEvent',
  full_name='eventstreaming.StoredEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='eventid', full_name='eventstreaming.StoredEvent.eventid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event', full_name='eventstreaming.StoredEvent.event', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=277,
  serialized_end=322,
)

_EVENTREQUEST.fields_by_name['type'].enum_type = _EVENTREQUEST_EVENTREQUESTTYPE
_EVENTREQUEST.fields_by_name['event_range'].message_type = _EVENTSTREAMRANGEREQUEST
_EVENTREQUEST_EVENTREQUESTTYPE.containing_type = _EVENTREQUEST;
DESCRIPTOR.message_types_by_name['EventRequest'] = _EVENTREQUEST
DESCRIPTOR.message_types_by_name['EventStreamRangeRequest'] = _EVENTSTREAMRANGEREQUEST
DESCRIPTOR.message_types_by_name['StoredEvent'] = _STOREDEVENT

class EventRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTREQUEST
  
  # @@protoc_insertion_point(class_scope:eventstreaming.EventRequest)

class EventStreamRangeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTSTREAMRANGEREQUEST
  
  # @@protoc_insertion_point(class_scope:eventstreaming.EventStreamRangeRequest)

class StoredEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STOREDEVENT
  
  # @@protoc_insertion_point(class_scope:eventstreaming.StoredEvent)

# @@protoc_insertion_point(module_scope)
