# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='commands.proto',
  package='commands',
  serialized_pb='\n\x0e\x63ommands.proto\x12\x08\x63ommands\"\xe4\x03\n\x07\x43ommand\x12+\n\x04type\x18\x01 \x02(\x0e\x32\x1d.commands.Command.CommandType\x12)\n\x0b\x63reate_task\x18\x02 \x01(\x0b\x32\x14.commands.CreateTask\x12,\n\rset_task_name\x18\x03 \x01(\x0b\x32\x15.commands.SetTaskName\x12:\n\x14set_task_description\x18\x04 \x01(\x0b\x32\x1c.commands.SetTaskDescription\x12+\n\x0c\x61rchive_task\x18\x05 \x01(\x0b\x32\x15.commands.ArchiveTask\x12/\n\x0eunarchive_task\x18\x06 \x01(\x0b\x32\x17.commands.UnarchiveTask\"\xb8\x01\n\x0b\x43ommandType\x12\x0f\n\x0b\x43REATE_TASK\x10\x02\x12\x11\n\rSET_TASK_NAME\x10\x03\x12\x12\n\x0eMARK_COMPLETED\x10\x04\x12\x16\n\x12MARK_NOT_COMPLETED\x10\x05\x12\x18\n\x14SET_TASK_DESCRIPTION\x10\x06\x12\x10\n\x0c\x41RCHIVE_TASK\x10\x07\x12\x12\n\x0eUNARCHIVE_TASK\x10\x08\x12\x19\n\x15\x41RCHIVE_ALL_COMPLETED\x10\t\"-\n\nCreateTask\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x0f\n\x07ownerid\x18\x02 \x02(\t\"+\n\x0bSetTaskName\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"9\n\x12SetTaskDescription\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\"\x1d\n\x0b\x41rchiveTask\x12\x0e\n\x06taskid\x18\x01 \x02(\t\"\x1f\n\rUnarchiveTask\x12\x0e\n\x06taskid\x18\x01 \x02(\t')



_COMMAND_COMMANDTYPE = descriptor.EnumDescriptor(
  name='CommandType',
  full_name='commands.Command.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CREATE_TASK', index=0, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SET_TASK_NAME', index=1, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MARK_COMPLETED', index=2, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MARK_NOT_COMPLETED', index=3, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SET_TASK_DESCRIPTION', index=4, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARCHIVE_TASK', index=5, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNARCHIVE_TASK', index=6, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARCHIVE_ALL_COMPLETED', index=7, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=329,
  serialized_end=513,
)


_COMMAND = descriptor.Descriptor(
  name='Command',
  full_name='commands.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='commands.Command.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='create_task', full_name='commands.Command.create_task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='set_task_name', full_name='commands.Command.set_task_name', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='set_task_description', full_name='commands.Command.set_task_description', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='archive_task', full_name='commands.Command.archive_task', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unarchive_task', full_name='commands.Command.unarchive_task', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_COMMANDTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=513,
)


_CREATETASK = descriptor.Descriptor(
  name='CreateTask',
  full_name='commands.CreateTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='commands.CreateTask.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ownerid', full_name='commands.CreateTask.ownerid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=515,
  serialized_end=560,
)


_SETTASKNAME = descriptor.Descriptor(
  name='SetTaskName',
  full_name='commands.SetTaskName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='commands.SetTaskName.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='commands.SetTaskName.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=562,
  serialized_end=605,
)


_SETTASKDESCRIPTION = descriptor.Descriptor(
  name='SetTaskDescription',
  full_name='commands.SetTaskDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='commands.SetTaskDescription.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='commands.SetTaskDescription.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=607,
  serialized_end=664,
)


_ARCHIVETASK = descriptor.Descriptor(
  name='ArchiveTask',
  full_name='commands.ArchiveTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='commands.ArchiveTask.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=666,
  serialized_end=695,
)


_UNARCHIVETASK = descriptor.Descriptor(
  name='UnarchiveTask',
  full_name='commands.UnarchiveTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='commands.UnarchiveTask.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=697,
  serialized_end=728,
)

_COMMAND.fields_by_name['type'].enum_type = _COMMAND_COMMANDTYPE
_COMMAND.fields_by_name['create_task'].message_type = _CREATETASK
_COMMAND.fields_by_name['set_task_name'].message_type = _SETTASKNAME
_COMMAND.fields_by_name['set_task_description'].message_type = _SETTASKDESCRIPTION
_COMMAND.fields_by_name['archive_task'].message_type = _ARCHIVETASK
_COMMAND.fields_by_name['unarchive_task'].message_type = _UNARCHIVETASK
_COMMAND_COMMANDTYPE.containing_type = _COMMAND;
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['CreateTask'] = _CREATETASK
DESCRIPTOR.message_types_by_name['SetTaskName'] = _SETTASKNAME
DESCRIPTOR.message_types_by_name['SetTaskDescription'] = _SETTASKDESCRIPTION
DESCRIPTOR.message_types_by_name['ArchiveTask'] = _ARCHIVETASK
DESCRIPTOR.message_types_by_name['UnarchiveTask'] = _UNARCHIVETASK

class Command(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND
  
  # @@protoc_insertion_point(class_scope:commands.Command)

class CreateTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATETASK
  
  # @@protoc_insertion_point(class_scope:commands.CreateTask)

class SetTaskName(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETTASKNAME
  
  # @@protoc_insertion_point(class_scope:commands.SetTaskName)

class SetTaskDescription(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETTASKDESCRIPTION
  
  # @@protoc_insertion_point(class_scope:commands.SetTaskDescription)

class ArchiveTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARCHIVETASK
  
  # @@protoc_insertion_point(class_scope:commands.ArchiveTask)

class UnarchiveTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNARCHIVETASK
  
  # @@protoc_insertion_point(class_scope:commands.UnarchiveTask)

# @@protoc_insertion_point(module_scope)
