# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import events_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='eventhandling.proto',
  package='eventstreaming',
  serialized_pb='\n\x13\x65venthandling.proto\x12\x0e\x65ventstreaming\x1a\x0c\x65vents.proto\"\xd1\x01\n\x15\x45ventStreamingCommand\x12P\n\x07\x63ommand\x18\x01 \x02(\x0e\x32?.eventstreaming.EventStreamingCommand.EventStreamingCommandType\x12\x35\n\x0b\x65vent_range\x18\x02 \x01(\x0b\x32 .eventstreaming.EventStreamRange\"/\n\x19\x45ventStreamingCommandType\x12\x12\n\x0eSTREAM_FROM_TO\x10\x02\",\n\x10\x45ventStreamRange\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\":\n\x1a\x45ventStreamingResponsePart\x12\x1c\n\x05\x65vent\x18\x01 \x01(\x0b\x32\r.events.Event')



_EVENTSTREAMINGCOMMAND_EVENTSTREAMINGCOMMANDTYPE = descriptor.EnumDescriptor(
  name='EventStreamingCommandType',
  full_name='eventstreaming.EventStreamingCommand.EventStreamingCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STREAM_FROM_TO', index=0, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=216,
  serialized_end=263,
)


_EVENTSTREAMINGCOMMAND = descriptor.Descriptor(
  name='EventStreamingCommand',
  full_name='eventstreaming.EventStreamingCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='eventstreaming.EventStreamingCommand.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_range', full_name='eventstreaming.EventStreamingCommand.event_range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTSTREAMINGCOMMAND_EVENTSTREAMINGCOMMANDTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=263,
)


_EVENTSTREAMRANGE = descriptor.Descriptor(
  name='EventStreamRange',
  full_name='eventstreaming.EventStreamRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='from', full_name='eventstreaming.EventStreamRange.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to', full_name='eventstreaming.EventStreamRange.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=265,
  serialized_end=309,
)


_EVENTSTREAMINGRESPONSEPART = descriptor.Descriptor(
  name='EventStreamingResponsePart',
  full_name='eventstreaming.EventStreamingResponsePart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='event', full_name='eventstreaming.EventStreamingResponsePart.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=311,
  serialized_end=369,
)

_EVENTSTREAMINGCOMMAND.fields_by_name['command'].enum_type = _EVENTSTREAMINGCOMMAND_EVENTSTREAMINGCOMMANDTYPE
_EVENTSTREAMINGCOMMAND.fields_by_name['event_range'].message_type = _EVENTSTREAMRANGE
_EVENTSTREAMINGCOMMAND_EVENTSTREAMINGCOMMANDTYPE.containing_type = _EVENTSTREAMINGCOMMAND;
_EVENTSTREAMINGRESPONSEPART.fields_by_name['event'].message_type = events_pb2._EVENT
DESCRIPTOR.message_types_by_name['EventStreamingCommand'] = _EVENTSTREAMINGCOMMAND
DESCRIPTOR.message_types_by_name['EventStreamRange'] = _EVENTSTREAMRANGE
DESCRIPTOR.message_types_by_name['EventStreamingResponsePart'] = _EVENTSTREAMINGRESPONSEPART

class EventStreamingCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTSTREAMINGCOMMAND
  
  # @@protoc_insertion_point(class_scope:eventstreaming.EventStreamingCommand)

class EventStreamRange(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTSTREAMRANGE
  
  # @@protoc_insertion_point(class_scope:eventstreaming.EventStreamRange)

class EventStreamingResponsePart(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTSTREAMINGRESPONSEPART
  
  # @@protoc_insertion_point(class_scope:eventstreaming.EventStreamingResponsePart)

# @@protoc_insertion_point(module_scope)
