# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='events.proto',
  package='events',
  serialized_pb='\n\x0c\x65vents.proto\x12\x06\x65vents\"\xbe\x03\n\x05\x45vent\x12%\n\x04type\x18\x01 \x02(\x0e\x32\x17.events.Event.EventType\x12)\n\x0ctask_created\x18\x03 \x01(\x0b\x32\x13.events.TaskCreated\x12*\n\rtask_name_set\x18\x04 \x01(\x0b\x32\x13.events.TaskNameSet\x12\x38\n\x14task_description_set\x18\x05 \x01(\x0b\x32\x1a.events.TaskDescriptionSet\x12+\n\rtask_archived\x18\x06 \x01(\x0b\x32\x14.events.TaskArchived\x12/\n\x0ftask_unarchived\x18\x07 \x01(\x0b\x32\x16.events.TaskUnarchived\"\x9e\x01\n\tEventType\x12\x12\n\x0eTASK_COMPLETED\x10\x01\x12\x16\n\x12TASK_NOT_COMPLETED\x10\x02\x12\x10\n\x0cTASK_CREATED\x10\x03\x12\x11\n\rTASK_NAME_SET\x10\x04\x12\x18\n\x14TASK_DESCRIPTION_SET\x10\x05\x12\x11\n\rTASK_ARCHIVED\x10\x06\x12\x13\n\x0fTASK_UNARCHIVED\x10\x07\"<\n\x0bStoredEvent\x12\x0f\n\x07\x65ventid\x18\x01 \x02(\t\x12\x1c\n\x05\x65vent\x18\x02 \x02(\x0b\x32\r.events.Event\".\n\x0bTaskCreated\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x0f\n\x07ownerid\x18\x02 \x02(\t\"+\n\x0bTaskNameSet\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"9\n\x12TaskDescriptionSet\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\"\x1e\n\x0cTaskArchived\x12\x0e\n\x06taskid\x18\x01 \x02(\t\" \n\x0eTaskUnarchived\x12\x0e\n\x06taskid\x18\x01 \x02(\t')



_EVENT_EVENTTYPE = descriptor.EnumDescriptor(
  name='EventType',
  full_name='events.Event.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TASK_COMPLETED', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_NOT_COMPLETED', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_CREATED', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_NAME_SET', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_DESCRIPTION_SET', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_ARCHIVED', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_UNARCHIVED', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=471,
)


_EVENT = descriptor.Descriptor(
  name='Event',
  full_name='events.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='events.Event.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_created', full_name='events.Event.task_created', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_name_set', full_name='events.Event.task_name_set', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_description_set', full_name='events.Event.task_description_set', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_archived', full_name='events.Event.task_archived', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task_unarchived', full_name='events.Event.task_unarchived', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_EVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=471,
)


_STOREDEVENT = descriptor.Descriptor(
  name='StoredEvent',
  full_name='events.StoredEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='eventid', full_name='events.StoredEvent.eventid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event', full_name='events.StoredEvent.event', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=473,
  serialized_end=533,
)


_TASKCREATED = descriptor.Descriptor(
  name='TaskCreated',
  full_name='events.TaskCreated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='events.TaskCreated.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ownerid', full_name='events.TaskCreated.ownerid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=535,
  serialized_end=581,
)


_TASKNAMESET = descriptor.Descriptor(
  name='TaskNameSet',
  full_name='events.TaskNameSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='events.TaskNameSet.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='events.TaskNameSet.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=583,
  serialized_end=626,
)


_TASKDESCRIPTIONSET = descriptor.Descriptor(
  name='TaskDescriptionSet',
  full_name='events.TaskDescriptionSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='events.TaskDescriptionSet.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='events.TaskDescriptionSet.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=628,
  serialized_end=685,
)


_TASKARCHIVED = descriptor.Descriptor(
  name='TaskArchived',
  full_name='events.TaskArchived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='events.TaskArchived.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=687,
  serialized_end=717,
)


_TASKUNARCHIVED = descriptor.Descriptor(
  name='TaskUnarchived',
  full_name='events.TaskUnarchived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='events.TaskUnarchived.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=719,
  serialized_end=751,
)

_EVENT.fields_by_name['type'].enum_type = _EVENT_EVENTTYPE
_EVENT.fields_by_name['task_created'].message_type = _TASKCREATED
_EVENT.fields_by_name['task_name_set'].message_type = _TASKNAMESET
_EVENT.fields_by_name['task_description_set'].message_type = _TASKDESCRIPTIONSET
_EVENT.fields_by_name['task_archived'].message_type = _TASKARCHIVED
_EVENT.fields_by_name['task_unarchived'].message_type = _TASKUNARCHIVED
_EVENT_EVENTTYPE.containing_type = _EVENT;
_STOREDEVENT.fields_by_name['event'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['StoredEvent'] = _STOREDEVENT
DESCRIPTOR.message_types_by_name['TaskCreated'] = _TASKCREATED
DESCRIPTOR.message_types_by_name['TaskNameSet'] = _TASKNAMESET
DESCRIPTOR.message_types_by_name['TaskDescriptionSet'] = _TASKDESCRIPTIONSET
DESCRIPTOR.message_types_by_name['TaskArchived'] = _TASKARCHIVED
DESCRIPTOR.message_types_by_name['TaskUnarchived'] = _TASKUNARCHIVED

class Event(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENT
  
  # @@protoc_insertion_point(class_scope:events.Event)

class StoredEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STOREDEVENT
  
  # @@protoc_insertion_point(class_scope:events.StoredEvent)

class TaskCreated(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKCREATED
  
  # @@protoc_insertion_point(class_scope:events.TaskCreated)

class TaskNameSet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKNAMESET
  
  # @@protoc_insertion_point(class_scope:events.TaskNameSet)

class TaskDescriptionSet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKDESCRIPTIONSET
  
  # @@protoc_insertion_point(class_scope:events.TaskDescriptionSet)

class TaskArchived(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKARCHIVED
  
  # @@protoc_insertion_point(class_scope:events.TaskArchived)

class TaskUnarchived(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKUNARCHIVED
  
  # @@protoc_insertion_point(class_scope:events.TaskUnarchived)

# @@protoc_insertion_point(module_scope)
