# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='queries.proto',
  package='queries',
  serialized_pb='\n\rqueries.proto\x12\x07queries\"\xb1\x01\n\x05Query\x12&\n\x04type\x18\x01 \x02(\x0e\x32\x18.queries.Query.QueryType\x12\x11\n\trequester\x18\x02 \x01(\t\"m\n\tQueryType\x12\x18\n\x14GET_TOTAL_TASK_COUNT\x10\x01\x12\x1a\n\x16GET_NON_ARCHIVED_TASKS\x10\x02\x12\x16\n\x12GET_ARCHIVED_TASKS\x10\x03\x12\x12\n\x0eGET_NEXT_TASKS\x10\x04\"L\n\x04Task\x12\x0e\n\x06taskid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"1\n\x11GetAllTasksResult\x12\x1c\n\x05tasks\x18\x01 \x03(\x0b\x32\r.queries.Task')



_QUERY_QUERYTYPE = descriptor.EnumDescriptor(
  name='QueryType',
  full_name='queries.Query.QueryType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GET_TOTAL_TASK_COUNT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_NON_ARCHIVED_TASKS', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_ARCHIVED_TASKS', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_NEXT_TASKS', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=95,
  serialized_end=204,
)


_QUERY = descriptor.Descriptor(
  name='Query',
  full_name='queries.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='queries.Query.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='requester', full_name='queries.Query.requester', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERY_QUERYTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=204,
)


_TASK = descriptor.Descriptor(
  name='Task',
  full_name='queries.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskid', full_name='queries.Task.taskid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='queries.Task.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='queries.Task.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='completed', full_name='queries.Task.completed', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=206,
  serialized_end=282,
)


_GETALLTASKSRESULT = descriptor.Descriptor(
  name='GetAllTasksResult',
  full_name='queries.GetAllTasksResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tasks', full_name='queries.GetAllTasksResult.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=284,
  serialized_end=333,
)

_QUERY.fields_by_name['type'].enum_type = _QUERY_QUERYTYPE
_QUERY_QUERYTYPE.containing_type = _QUERY;
_GETALLTASKSRESULT.fields_by_name['tasks'].message_type = _TASK
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['GetAllTasksResult'] = _GETALLTASKSRESULT

class Query(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERY
  
  # @@protoc_insertion_point(class_scope:queries.Query)

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK
  
  # @@protoc_insertion_point(class_scope:queries.Task)

class GetAllTasksResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETALLTASKSRESULT
  
  # @@protoc_insertion_point(class_scope:queries.GetAllTasksResult)

# @@protoc_insertion_point(module_scope)
